group: travis_lts
sudo: required
# From https://gist.github.com/gocanto/46b8d39576f612f9c6b8b4ffb3efac98
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
language: python
python:
  - "2.7"
install:
  - pip install -U pip setuptools
  - pip install coveralls
before_script:
  - mysql --version
  - mysql -e 'CREATE DATABASE travis_ci_test;'
script:
  - coverage run --source=misago setup.py test
