# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0006_redo_partial_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text=b'Discussion ID from legacy IWC Forum', null=True),
        ),
    ]
