# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0007_thread_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='Post ID from legacy IWC Forum', null=True),
        ),
    ]
