# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-14 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_threads', '0007_auto_20171008_0131'),
        ('misago_threads', '0008_post_legacy_id'),
    ]

    operations = [
    ]
