# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 05:12
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0008_ban_registration_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_fields',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
