# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 22:15
from __future__ import unicode_literals

from extras.oms_json.fields import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0009_redo_partial_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_fields',
            field=JSONField(default=dict),
        ),
    ]
